flix_original/config/routes.rb
Rails.application.routes.draw do
  root "movies#index" 
  get "/movies" => "movies#index"
  get "movies/:id" => "movies#show", as: "movie"
end

flix_original/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

flix_original/app/models/movie.rb
class Movie < ApplicationRecord
  def flop?
    total_gross.blank? || total_gross < 50000000
  end
end

flix_original/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

flix_original/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

flix_original/app/helpers/application_helper.rb
module ApplicationHelper
end

flix_original/app/helpers/movies_helper.rb
module MoviesHelper
  def format_total_gross(movie)
    if movie.flop?
      content_tag(:strong, 'Flop!')
      # or "<strong>Flop!</strong>".html_safe
    else
      number_to_currency(movie.total_gross)
    end
  end
end

flix_original/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

flix_original/app/views/movies/index.html.erb
<h1><%= pluralize(@movies.size, 'Movie') %></h1>

<% @movies.each do |movie| %>
  <article>
    <header>
      <h2><%= link_to(movie.title, movie) %></h2>
      <%# <h2><%= link_to(movie.title, movie_path(movie.id))%></h2> 
      <%# <h2><%= link_to(movie.title, movie_path(movie))%></h2> 
    </header>
    <p>
      <%= truncate(movie.description, length: 40, separator: ' ') %>
    </p>
    <table>
      <tr>
        <th>Released:</th>
        <td><%= movie.released_on %> (<%= time_ago_in_words(movie.released_on) %> ago)</td>
      </tr>
      <tr>
        <th>Rating:</th>
        <td><%= movie.rating %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
        <td><%= format_total_gross(movie) %></td>
      </tr>
    </table>
  </article>
<% end %>

flix_original/app/views/movies/show.html.erb
<article>
  <header>
    <h1><%= @movie.title %></h1>
  </header>
  <h2>Description</h2>
  <p>
    <%= @movie.description %>
  </p>
  <h3>Rating</h3>
  <p>
    <%= @movie.rating %>
  </p>
  <h3>Released On</h3>
  <p>
    <%= @movie.released_on %>
  </p>
  <h3>Total Gross</h3>
  <p>
    <%= format_total_gross(@movie) %>
  </p>
</article>

<p><%= link_to 'All Movies', root_path %></p>